version: '2'

services:
  Modeling-micoservice:
    image: 'miejscowka-occupancy-modeling:latest'
    ports:
      - "8070:8070"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/MiejscowkaOccupancyModeling
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "5050:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MiejscowkaOccupancyModeling
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U MiejscowkaOccupancyModeling" ]
      interval: 10s
      timeout: 5s
      retries: 5
